"""
AI Intelligence Center — Database models.

Tables:
  ai_anomalies          — detected anomalies from all modules
  ai_risk_scores        — per-entity risk scores with history
  ai_alerts             — smart alerts for suspicious activity
  ai_duplicate_matches  — detected duplicate records
  ai_queries            — natural language query log
  ai_insights           — generated insight summaries
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import (
    Boolean, Column, DateTime, Float, ForeignKey,
    Integer, String, Text,
)
from sqlalchemy.orm import relationship

from app.core.database import Base


# ── Anomaly Records ───────────────────────────────────────────────────────────

class AIAnomaly(Base):
    """Detected anomaly from any module."""
    __tablename__ = "ai_anomalies"

    id            = Column(Integer, primary_key=True, index=True)
    company_id    = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    anomaly_type  = Column(String(80), nullable=False, index=True)
    # e.g. HIGH_EXPENSE | BACKDATED_ENTRY | AFTER_HOURS | RAPID_EDITS | LARGE_JUMP | DUPLICATE
    severity      = Column(String(20), nullable=False, default="MEDIUM", index=True)
    # LOW | MEDIUM | HIGH | CRITICAL
    module        = Column(String(50), nullable=True, index=True)
    entity_type   = Column(String(80), nullable=True)
    entity_id     = Column(Integer, nullable=True)
    user_id       = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    description   = Column(Text, nullable=False)
    details       = Column(Text, nullable=True)   # JSON
    risk_score    = Column(Float, nullable=False, default=0.0)
    is_resolved   = Column(Boolean, nullable=False, default=False, index=True)
    resolved_by   = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    resolved_at   = Column(DateTime, nullable=True)
    created_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    user          = relationship("User", foreign_keys=[user_id])
    resolver      = relationship("User", foreign_keys=[resolved_by])


# ── Risk Scores ───────────────────────────────────────────────────────────────

class AIRiskScore(Base):
    """Dynamic risk score for a user or entity."""
    __tablename__ = "ai_risk_scores"

    id            = Column(Integer, primary_key=True, index=True)
    company_id    = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    subject_type  = Column(String(40), nullable=False, index=True)   # user | finance_entry | tenant | property
    subject_id    = Column(Integer, nullable=False, index=True)
    score         = Column(Float, nullable=False, default=0.0)
    risk_level    = Column(String(20), nullable=False, default="LOW", index=True)
    # LOW | MEDIUM | HIGH | CRITICAL
    factors       = Column(Text, nullable=True)   # JSON list of contributing factors
    last_computed = Column(DateTime, default=datetime.utcnow, nullable=False)
    created_at    = Column(DateTime, default=datetime.utcnow, nullable=False)


# ── AI Alerts ─────────────────────────────────────────────────────────────────

class AIAlert(Base):
    """Smart alert generated by the AI engine."""
    __tablename__ = "ai_alerts"

    id            = Column(Integer, primary_key=True, index=True)
    company_id    = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    alert_type    = Column(String(80), nullable=False, index=True)
    # SUSPICIOUS_EDIT | DUPLICATE_FOUND | HIGH_RISK_USER | UNUSUAL_EXPENSE |
    # DELETED_FINANCE | BACKDATED | AFTER_HOURS | RAPID_EDITS | LARGE_TRANSACTION
    severity      = Column(String(20), nullable=False, default="MEDIUM", index=True)
    title         = Column(String(255), nullable=False)
    message       = Column(Text, nullable=False)
    module        = Column(String(50), nullable=True)
    entity_type   = Column(String(80), nullable=True)
    entity_id     = Column(Integer, nullable=True)
    user_id       = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    anomaly_id    = Column(Integer, ForeignKey("ai_anomalies.id", ondelete="SET NULL"), nullable=True)
    is_read       = Column(Boolean, nullable=False, default=False, index=True)
    is_dismissed  = Column(Boolean, nullable=False, default=False, index=True)
    created_at    = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    user          = relationship("User", foreign_keys=[user_id])
    anomaly       = relationship("AIAnomaly", foreign_keys=[anomaly_id])


# ── Duplicate Matches ─────────────────────────────────────────────────────────

class AIDuplicateMatch(Base):
    """Detected duplicate record pair."""
    __tablename__ = "ai_duplicate_matches"

    id              = Column(Integer, primary_key=True, index=True)
    company_id      = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    entity_type     = Column(String(80), nullable=False, index=True)
    # tenant | property | client | finance_entry
    entity_id_a     = Column(Integer, nullable=False)
    entity_id_b     = Column(Integer, nullable=False)
    confidence      = Column(Float, nullable=False)   # 0.0 – 1.0
    match_fields    = Column(Text, nullable=True)     # JSON: which fields matched
    status          = Column(String(20), nullable=False, default="pending", index=True)
    # pending | confirmed | dismissed | merged
    reviewed_by     = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True)
    reviewed_at     = Column(DateTime, nullable=True)
    created_at      = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    reviewer        = relationship("User", foreign_keys=[reviewed_by])


# ── Natural Language Queries ──────────────────────────────────────────────────

class AIQuery(Base):
    """Log of natural language queries submitted by users."""
    __tablename__ = "ai_queries"

    id              = Column(Integer, primary_key=True, index=True)
    company_id      = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    user_id         = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    raw_query       = Column(Text, nullable=False)
    detected_intent = Column(String(80), nullable=True)
    # SUSPICIOUS_TRANSACTIONS | DELETED_FINANCE | TOP_EDITORS | HIGH_RISK_USERS |
    # DUPLICATE_TENANTS | RENT_RECOVERY | ANOMALY_SUMMARY | AUDIT_TRAIL | UNKNOWN
    mapped_query    = Column(Text, nullable=True)    # The safe SQL template used
    result_summary  = Column(Text, nullable=True)    # AI-generated summary of results
    result_count    = Column(Integer, nullable=True)
    execution_ms    = Column(Integer, nullable=True)
    was_blocked     = Column(Boolean, nullable=False, default=False)
    block_reason    = Column(String(255), nullable=True)
    created_at      = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)

    user            = relationship("User", foreign_keys=[user_id])


# ── AI Insight Summaries ──────────────────────────────────────────────────────

class AIInsight(Base):
    """Generated insight summary (daily / weekly / monthly)."""
    __tablename__ = "ai_insights"

    id              = Column(Integer, primary_key=True, index=True)
    company_id      = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False, index=True)
    period_type     = Column(String(20), nullable=False, index=True)   # daily | weekly | monthly
    period_label    = Column(String(40), nullable=False)               # e.g. "2026-05-08" | "2026-W19"
    summary_text    = Column(Text, nullable=False)
    metrics         = Column(Text, nullable=True)   # JSON: key metrics used to generate
    anomaly_count   = Column(Integer, nullable=False, default=0)
    alert_count     = Column(Integer, nullable=False, default=0)
    duplicate_count = Column(Integer, nullable=False, default=0)
    high_risk_count = Column(Integer, nullable=False, default=0)
    created_at      = Column(DateTime, default=datetime.utcnow, nullable=False, index=True)
