/**
 * Chat Service Abstraction Layer
 *
 * Pluggable real-time messaging layer. Currently runs in DEMO MODE with
 * local state. To activate real backend integration:
 *   1. Connect FastAPI WebSocket endpoint (/ws/chat)
 *   2. Replace stub implementations with real API calls
 *   3. The store already handles WebSocket dispatch via useChatStore.receiveWsEvent()
 *
 * Architecture:
 *   UI → ChatService → (WebSocket / REST) → FastAPI → broadcast to all clients
 *
 * System events are auto-generated by admin actions and pushed into the
 * "System Updates" channel visible to all roles.
 */

// ── Message types ─────────────────────────────────────────────────────────────

export type MessageType = "user_message" | "system_message" | "event_message";

export type SystemEventType =
  | "USER_CREATED"   | "USER_DELETED"   | "USER_UPDATED"
  | "ROLE_UPDATED"   | "PROPERTY_ADDED" | "PROPERTY_UPDATED"
  | "FINANCE_ENTRY"  | "TENANT_ADDED"   | "MAINTENANCE_CREATED"
  | "BOOKING_CREATED"| "DEAL_CLOSED"    | "PAYMENT_RECEIVED"
  | "GENERIC";

export interface ChatMessage {
  id:          string;
  channelId:   string;
  type:        MessageType;
  senderId:    string | null;   // null for system messages
  senderName:  string;
  senderRole:  string;
  body:        string;
  timestamp:   Date;
  status:      "sent" | "delivered" | "read";
  eventType?:  SystemEventType;
  metadata?:   Record<string, string>;  // extra context for event messages
  isSystem:    boolean;
}

export interface ChatChannel {
  id:          string;
  name:        string;
  type:        "direct" | "group" | "system" | "role";
  roleId?:     number | null;
  roleName?:   string | null;
  members:     string[];   // user IDs
  unread:      number;
  lastMessage: string;
  lastTime:    Date;
  pinned:      boolean;
  icon?:       string;
}

// ── System event → human-readable message ────────────────────────────────────

export function formatSystemEvent(
  eventType: SystemEventType,
  payload: Record<string, string>,
): string {
  switch (eventType) {
    case "USER_CREATED":    return `👤 New user added: ${payload.name ?? "Unknown"} as ${payload.role ?? "User"}`;
    case "USER_DELETED":    return `❌ User removed from system: ${payload.name ?? "Unknown"}`;
    case "USER_UPDATED":    return `✏️ User profile updated: ${payload.name ?? "Unknown"}`;
    case "ROLE_UPDATED":    return `🔄 User role updated: ${payload.name ?? "Unknown"} → ${payload.newRole ?? "Unknown"}`;
    case "PROPERTY_ADDED":  return `🏠 New property registered: ${payload.name ?? "Unknown"}`;
    case "PROPERTY_UPDATED":return `🏠 Property updated: ${payload.name ?? "Unknown"}`;
    case "FINANCE_ENTRY":   return `💰 New financial record created by ${payload.by ?? "Admin"}: ${payload.description ?? ""}`;
    case "TENANT_ADDED":    return `🏘️ New tenant added: ${payload.name ?? "Unknown"}`;
    case "MAINTENANCE_CREATED": return `🔧 Maintenance request created: ${payload.title ?? "Unknown"} at ${payload.property ?? ""}`;
    case "BOOKING_CREATED": return `📋 New booking created: ${payload.bookingId ?? ""} — ${payload.client ?? "Unknown"}`;
    case "DEAL_CLOSED":     return `🤝 Deal closed: ${payload.dealId ?? ""} — ${payload.client ?? "Unknown"}`;
    case "PAYMENT_RECEIVED":return `💳 Payment received: ${payload.amount ?? ""} from ${payload.client ?? "Unknown"}`;
    default:                return `⚙️ System event: ${payload.description ?? eventType}`;
  }
}

// ── Service stubs ─────────────────────────────────────────────────────────────

export const ChatService = {
  /**
   * Send a user message to a channel.
   * Demo: handled entirely in store.
   * Real: POST /api/chat/messages
   */
  async sendMessage(
    _channelId: string,
    _body: string,
    _senderId: string,
  ): Promise<{ success: boolean; messageId?: string }> {
    return { success: true, messageId: `msg_${Date.now()}` };
  },

  /**
   * Broadcast a system event message to the system channel.
   * Demo: handled in store.
   * Real: POST /api/chat/system-event  (called by backend after DB action)
   */
  async sendSystemMessage(
    eventType: SystemEventType,
    payload: Record<string, string>,
  ): Promise<void> {
    // TODO: POST to backend which then broadcasts via WebSocket
    // await api.post("/chat/system-event", { eventType, payload });
    void eventType; void payload;
  },

  /**
   * Broadcast an event to all connected clients.
   * Real: backend WebSocket broadcast.
   */
  async broadcastEvent(
    _eventType: SystemEventType,
    _payload: Record<string, string>,
  ): Promise<void> {
    // TODO: backend handles this — frontend just receives via WS
  },

  /**
   * Fetch message history for a channel.
   * Demo: store manages local state.
   * Real: GET /api/chat/channels/:id/messages
   */
  async getMessages(_channelId: string): Promise<ChatMessage[]> {
    return [];
  },
};
