from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle,
    Paragraph, Spacer, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from io import BytesIO
from datetime import datetime
from typing import List, Dict, Any, Optional


def generate_table_report(
    title: str,
    columns: List[str],
    column_keys: List[str],
    data: List[Dict[str, Any]],
    subtitle: Optional[str] = None,
    company_name: Optional[str] = "Real Estate ERP",
    generated_by: Optional[str] = "System",
    date_range: Optional[str] = None,
    summary_row: Optional[Dict[str, str]] = None
) -> BytesIO:
    """
    Generate a professional PDF report with a table.

    Args:
        title: Report title shown at top
        columns: List of column header labels
        column_keys: List of dict keys to pull values from each data row
        data: List of dicts — each dict is one row
        subtitle: Optional subtitle below title
        company_name: Company name shown in header
        generated_by: Username of who generated the report
        date_range: e.g. "01/01/2026 - 03/06/2026"
        summary_row: Optional dict of summary values for last row

    Returns:
        BytesIO buffer containing the PDF — seek(0) before returning to client
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=15 * mm,
        leftMargin=15 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Title'],
        fontSize=16,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#111827'),
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontSize=10,
        fontName='Helvetica',
        textColor=colors.HexColor('#6B7280'),
        spaceAfter=2
    )

    meta_style = ParagraphStyle(
        'ReportMeta',
        parent=styles['Normal'],
        fontSize=9,
        fontName='Helvetica',
        textColor=colors.HexColor('#9CA3AF'),
        spaceAfter=0
    )

    elements = []

    # ── HEADER ──────────────────────────────────────────
    elements.append(Paragraph(company_name, subtitle_style))
    elements.append(Paragraph(title, title_style))

    if subtitle:
        elements.append(Paragraph(subtitle, subtitle_style))

    if date_range:
        elements.append(Paragraph(f"Period: {date_range}", meta_style))

    elements.append(Paragraph(
        f"Generated by: {generated_by}  |  Date: "
        f"{datetime.now().strftime('%d/%m/%Y %I:%M %p')}",
        meta_style
    ))

    elements.append(Spacer(1, 4 * mm))
    elements.append(HRFlowable(
        width="100%", thickness=1,
        color=colors.HexColor('#E5E7EB'), spaceAfter=4 * mm
    ))

    # ── TABLE ────────────────────────────────────────────
    if not data:
        elements.append(Paragraph(
            "No data found for the selected filters.",
            subtitle_style
        ))
    else:
        # Build table rows
        header_row = columns
        table_rows = [header_row]

        for item in data:
            row = []
            for key in column_keys:
                value = item.get(key, '')
                if value is None:
                    value = '\u2014'
                row.append(str(value))
            table_rows.append(row)

        # Optional summary row at bottom
        if summary_row:
            summary = [summary_row.get(key, '') for key in column_keys]
            table_rows.append(summary)

        # Auto-calculate column widths
        page_width = A4[0] - 30 * mm  # total usable width
        col_width = page_width / len(columns)
        col_widths = [col_width] * len(columns)

        table = Table(table_rows, colWidths=col_widths, repeatRows=1)

        # Table styling
        style = TableStyle([
            # Header row
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1F2937')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 9),
            ('ALIGN', (0, 0), (-1, 0), 'LEFT'),
            ('TOPPADDING', (0, 0), (-1, 0), 8),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 8),
            ('LEFTPADDING', (0, 0), (-1, 0), 8),

            # Data rows
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 8),
            ('ALIGN', (0, 1), (-1, -1), 'LEFT'),
            ('TOPPADDING', (0, 1), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 1), (-1, -1), 6),
            ('LEFTPADDING', (0, 1), (-1, -1), 8),
            ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#111827')),

            # Alternating row colors
            ('ROWBACKGROUNDS', (0, 1), (-1, -1),
             [colors.HexColor('#F9FAFB'), colors.white]),

            # Grid
            ('GRID', (0, 0), (-1, -1), 0.4, colors.HexColor('#E5E7EB')),
            ('LINEBELOW', (0, 0), (-1, 0), 1, colors.HexColor('#374151')),
        ])

        # Summary row styling (last row if present)
        if summary_row:
            style.add('BACKGROUND', (0, -1), (-1, -1),
                      colors.HexColor('#F3F4F6'))
            style.add('FONTNAME', (0, -1), (-1, -1), 'Helvetica-Bold')
            style.add('LINEABOVE', (0, -1), (-1, -1),
                      1, colors.HexColor('#D1D5DB'))

        table.setStyle(style)
        elements.append(table)

    # ── FOOTER ───────────────────────────────────────────
    elements.append(Spacer(1, 6 * mm))
    elements.append(HRFlowable(
        width="100%", thickness=0.5,
        color=colors.HexColor('#E5E7EB'), spaceBefore=2 * mm
    ))
    elements.append(Paragraph(
        f"{company_name}  |  {title}  |  Confidential",
        meta_style
    ))

    # Build PDF
    doc.build(elements)
    buffer.seek(0)
    return buffer


def generate_statement_report(
    title: str,
    entity_info: Dict[str, str],
    columns: List[str],
    column_keys: List[str],
    data: List[Dict[str, Any]],
    opening_balance: Optional[float] = None,
    closing_balance: Optional[float] = None,
    company_name: Optional[str] = "Real Estate ERP",
    generated_by: Optional[str] = "System",
    date_range: Optional[str] = None,
) -> BytesIO:
    """
    Generate a statement-style PDF (Customer Ledger, Rent Ledger, etc.)
    with entity info block at top (client name, CNIC, etc.) then a table.
    """
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer, pagesize=A4,
        rightMargin=15*mm, leftMargin=15*mm,
        topMargin=20*mm, bottomMargin=20*mm
    )

    styles = getSampleStyleSheet()
    elements = []

    title_style = ParagraphStyle(
        'Title2', parent=styles['Normal'],
        fontSize=15, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#111827'), spaceAfter=3
    )
    label_style = ParagraphStyle(
        'Label', parent=styles['Normal'],
        fontSize=9, fontName='Helvetica-Bold',
        textColor=colors.HexColor('#374151')
    )
    value_style = ParagraphStyle(
        'Value', parent=styles['Normal'],
        fontSize=9, fontName='Helvetica',
        textColor=colors.HexColor('#111827')
    )
    meta_style = ParagraphStyle(
        'Meta2', parent=styles['Normal'],
        fontSize=8, textColor=colors.HexColor('#9CA3AF')
    )

    # Header
    elements.append(Paragraph(company_name, value_style))
    elements.append(Paragraph(title, title_style))
    if date_range:
        elements.append(Paragraph(f"Period: {date_range}", value_style))
    elements.append(Paragraph(
        f"Generated by: {generated_by}  |  "
        f"{datetime.now().strftime('%d/%m/%Y %I:%M %p')}",
        meta_style
    ))
    elements.append(Spacer(1, 3*mm))
    elements.append(HRFlowable(width="100%", thickness=1,
                               color=colors.HexColor('#E5E7EB'),
                               spaceAfter=3*mm))

    # Entity info block (2-column layout)
    if entity_info:
        info_data = [[
            Paragraph(k, label_style),
            Paragraph(str(v), value_style)
        ] for k, v in entity_info.items()]

        # Split into two side-by-side columns
        half = (len(info_data) + 1) // 2
        left_col = info_data[:half]
        right_col = info_data[half:]

        # Pad right col if shorter
        while len(right_col) < len(left_col):
            right_col.append([Paragraph('', label_style),
                               Paragraph('', value_style)])

        combined = [[l[0], l[1], r[0], r[1]]
                    for l, r in zip(left_col, right_col)]

        page_width = A4[0] - 30*mm
        info_table = Table(combined,
                           colWidths=[35*mm, 55*mm, 35*mm, 55*mm])
        info_table.setStyle(TableStyle([
            ('VALIGN', (0,0), (-1,-1), 'TOP'),
            ('TOPPADDING', (0,0), (-1,-1), 3),
            ('BOTTOMPADDING', (0,0), (-1,-1), 3),
        ]))
        elements.append(info_table)
        elements.append(Spacer(1, 4*mm))
        elements.append(HRFlowable(width="100%", thickness=0.5,
                                   color=colors.HexColor('#E5E7EB'),
                                   spaceAfter=3*mm))

    # Opening balance row
    if opening_balance is not None:
        elements.append(Paragraph(
            f"Opening Balance: PKR {opening_balance:,.2f}",
            label_style
        ))
        elements.append(Spacer(1, 2*mm))

    # Main table (reuse same logic as generate_table_report)
    if data:
        header_row = columns
        table_rows = [header_row]
        for item in data:
            row = [str(item.get(k, '\u2014') or '\u2014') for k in column_keys]
            table_rows.append(row)

        page_width = A4[0] - 30*mm
        col_width = page_width / len(columns)
        table = Table(table_rows,
                      colWidths=[col_width]*len(columns),
                      repeatRows=1)
        table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1F2937')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('ROWBACKGROUNDS', (0,1), (-1,-1),
             [colors.HexColor('#F9FAFB'), colors.white]),
            ('GRID', (0,0), (-1,-1), 0.4, colors.HexColor('#E5E7EB')),
            ('TOPPADDING', (0,0), (-1,-1), 5),
            ('BOTTOMPADDING', (0,0), (-1,-1), 5),
            ('LEFTPADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(table)

    # Closing balance
    if closing_balance is not None:
        elements.append(Spacer(1, 3*mm))
        elements.append(Paragraph(
            f"Closing Balance: PKR {closing_balance:,.2f}",
            label_style
        ))

    doc.build(elements)
    buffer.seek(0)
    return buffer
