import { useEffect, useState } from "react";
import { CheckCircle2, XCircle, DollarSign, Building2, CreditCard, Landmark, Smartphone, Printer } from "lucide-react";
import DataTable from '../../components/data-table/DataTable';
import { crmApi, PaymentLedgerEntry } from "../../lib/crmApi";

const METHOD_CONFIG: Record<string, { color: string; icon: React.ElementType }> = {
  cash: { color: "#10b981", icon: DollarSign },
  bank_transfer: { color: "#3b82f6", icon: Landmark },
  cheque: { color: "#8b5cf6", icon: Building2 },
  easypaisa: { color: "#ef4444", icon: Smartphone },
  jazzcash: { color: "#f59e0b", icon: Smartphone },
};

const TYPE_COLORS: Record<string, string> = {
  "Token": "#8b5cf6",
  "Down Payment": "#f59e0b",
  "Instalment": "#3b82f6",
  "Payment": "#10b981",
};

function MethodBadge({ method }: { method: string }) {
  const cfg = METHOD_CONFIG[method] ?? { color: "#94a3b8", icon: CreditCard };
  const Icon = cfg.icon;
  return (
    <span className="inline-flex items-center gap-1 text-xs" style={{ color: cfg.color }}>
      <Icon size={12} /> {method.replace("_", " ")}
    </span>
  );
}

function TypeBadge({ type }: { type: string }) {
  const color = TYPE_COLORS[type] ?? "#94a3b8";
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold"
      style={{ background: `${color}15`, color }}
    >
      {type}
    </span>
  );
}

function FinanceBadge({ posted }: { posted: boolean }) {
  if (posted) {
    return (
      <span className="inline-flex items-center gap-1 text-[10px] font-semibold" style={{ color: "#10b981" }}>
        <CheckCircle2 size={10} /> Posted
      </span>
    );
  }
  return (
    <span className="inline-flex items-center gap-1 text-[10px] font-semibold" style={{ color: "#94a3b8" }}>
      <XCircle size={10} /> Pending
    </span>
  );
}

function StatusBadge({ status }: { status: string }) {
  const isCompleted = status === "completed";
  return (
    <span
      className="inline-flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-semibold"
      style={{
        background: isCompleted ? "rgba(16,185,129,0.12)" : "rgba(245,158,11,0.12)",
        color: isCompleted ? "#10b981" : "#f59e0b",
      }}
    >
      {isCompleted ? <CheckCircle2 size={10} /> : null}
      {status}
    </span>
  );
}

function PaidDate({ value }: { value: string }) {
  if (!value) return <span className="text-xs" style={{ color: "var(--text-muted)" }}>—</span>;
  return (
    <span className="text-xs" style={{ color: "var(--text-secondary)" }}>
      {new Date(value).toLocaleDateString(undefined, { day: "numeric", month: "short", year: "numeric" })}
    </span>
  );
}

export default function Payments() {
  const [items, setItems] = useState<PaymentLedgerEntry[]>([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(true);
  const [page, setPage] = useState(1);

  const pageSize = 20;

  const fetch = async () => {
    setLoading(true);
    try {
      const res = await crmApi.getPaymentLedger({ limit: pageSize, offset: (page - 1) * pageSize });
      setItems(res.items ?? []);
      setTotal(res.total ?? 0);
    } catch { setItems([]); } finally { setLoading(false); }
  };

  useEffect(() => { void fetch(); }, [page]);

  const printReceipt = (entry: PaymentLedgerEntry) => {
    const w = window.open("", "_blank", "width=500,height=700");
    if (!w) return;
    w.document.write(`
      <html><head><title>Receipt - ${entry.pay_id}</title>
      <style>body{font-family:monospace;padding:40px;color:#222}h2{text-align:center}.receipt{border:1px dashed #ccc;padding:20px;margin-top:20px}.row{display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid #eee}</style>
      </head><body>
      <h2>PAYMENT RECEIPT</h2>
      <div class="receipt">
        <p><strong>Receipt #:</strong> ${entry.receipt || entry.pay_id}</p>
        <p><strong>Payment ID:</strong> ${entry.pay_id}</p>
        <p><strong>Client:</strong> ${entry.client_name || "—"}</p>
        <p><strong>Date:</strong> ${new Date(entry.date).toLocaleDateString()}</p>
        <p><strong>Type:</strong> ${entry.payment_type}</p>
        <p><strong>Reference:</strong> ${entry.reference || "—"}</p>
        <div class="row"><span>Method</span><span>${entry.method.replace("_", " ")}</span></div>
        <div class="row" style="font-size:18px;font-weight:bold"><span>Amount</span><span>PKR ${Number(entry.amount).toLocaleString()}</span></div>
        <p><strong>Finance:</strong> ${entry.finance_posted ? "Posted" : "Pending"}</p>
        ${entry.notes ? `<p style="margin-top:20px"><strong>Notes:</strong> ${entry.notes}</p>` : ""}
      </div>
      <p style="text-align:center;margin-top:30px;color:#999;font-size:11px">Generated by EyerREMS CRM</p>
      <script>window.print()</script>
      </body></html>
    `);
    w.document.close();
  };

  const totalAmount = items.reduce((s, p) => s + Number(p.amount), 0);

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs" style={{ color: "var(--text-muted)" }}>
            {total} transactions · Total: PKR {totalAmount.toLocaleString()}
          </p>
        </div>
      </div>

      <DataTable
        data={items}
        loading={loading}
        searchable={false}
        pagination={{ page, pageSize, total }}
        onPaginationChange={(config) => setPage(config.page)}
        columns={[
          { key: 'pay_id', label: 'PAY-ID', width: 110, render: (value: string) => <span className="font-mono text-xs" style={{ color: "#60a5fa" }}>{value}</span> },
          { key: 'date', label: 'Date', width: 110, render: (value: string) => <PaidDate value={value} /> },
          { key: 'client_name', label: 'Client', render: (_value: string, row: PaymentLedgerEntry) => <span className="text-xs font-medium" style={{ color: "var(--text-primary)" }}>{row.client_name ?? "—"}</span> },
          { key: 'reference', label: 'Reference', width: 120, render: (value: string | null) => <span className="text-xs font-mono" style={{ color: "var(--text-muted)" }}>{value ?? "—"}</span> },
          { key: 'payment_type', label: 'Type', width: 110, render: (value: string) => <TypeBadge type={value} /> },
          { key: 'amount', label: 'Amount', width: 120, align: 'right', render: (value: number) => <span className="text-xs font-semibold" style={{ color: "var(--text-primary)" }}>{Number(value).toLocaleString()}</span> },
          { key: 'method', label: 'Method', width: 120, render: (value: string) => <MethodBadge method={value} /> },
          { key: 'received_by', label: 'Received By', width: 110, render: (value: string | null) => <span className="text-xs" style={{ color: "var(--text-muted)" }}>{value ?? "—"}</span> },
          { key: 'receipt', label: 'Receipt', width: 100, render: (value: string | null) => <span className="text-xs font-mono" style={{ color: "var(--text-muted)" }}>{value ?? "—"}</span> },
          { key: 'finance_posted', label: 'Finance Posted', width: 100, align: 'center', render: (_value: boolean, row: PaymentLedgerEntry) => <FinanceBadge posted={row.finance_posted} /> },
          { key: 'status', label: 'Status', width: 100, align: 'center', render: (value: string) => <StatusBadge status={value} /> },
          { key: 'action', label: 'Actions', width: 80, align: 'right', render: (_value: string, row: PaymentLedgerEntry) => (
            <button onClick={() => printReceipt(row)} className="flex items-center gap-1 ml-auto text-[10px] px-2 py-1 rounded-lg" style={{ background: "rgba(59,130,246,0.1)", color: "#60a5fa" }}>
              <Printer size={11} /> Print
            </button>
          )},
        ]}
      />
    </div>
  );
}
